services:
    postgres_2:
        image: postgres:18-alpine

        container_name: nasa_db

        ports:
            - "5432:5432"

        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: nasa_db

        volumes:
            - nasa_postgres_data:/var/lib/postgresql

        restart: unless-stopped

        networks:
            - app-net

volumes:
    nasa_postgres_data:

networks:
    app-net:
        driver: bridge
